use_cuda: true
data_parallel: true
num_epochs: 450
output_dir: experiments/cifar10

model:
  name: efficientnet_b0
  num_classes: 10
  in_channels: 3

dataset:
  name: cifar10_dataloaders
  root: data
  batch_size: 256
  image_size: 32
  num_workers: 8

optimizer:
  name: SGD
  lr: 1.e-1
  weight_decay: 1.e-4
  momentum: 0.9
  nesterov: true

scheduler:
  name: StepLR
  step_size: 150
